name: Security Audit
on:
    schedule:
        - cron: "55 * * * *"
jobs:
    audit:
        name: Security Audit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Audit
              run: npm audit
